### ISSUE TITLE
Source ?

### ISSUE THREAD

**Issue by HorlogeSkynet** [ghqc/readme#1]
Hello ici !

_Why not_ ce petit projet "d'agrégat", mais où sont les sources de ce fameux bot ? 🙂

Cya 👋

**Comment by millette** [comment]
Bonjour,

J'hésitais à publier les sources parce que c'est un peu mal vu par GitHub de créer plus d'un compte par utilisateur.

D'ailleurs, le compte a été flaggué après 2-3 jours - beaucoup d'utilisateurs ont remarqué être suivi par un compte qui suivait déjà 10,000 utilisateurs, et l'ont bloqué. Ça pris une semaine de discussion avec GitHub pour rétablir ce compte.

Pour le data récolté, je comptais d'abord rendre ça disponible en tant que [dat](https://github.com/datproject/dat). Pour le moment, c'est disponible via la clé [019d05c89e9469d401730172b6eb52e7880c1550fda1720671f76c7229a80bae](dat://019d05c89e9469d401730172b6eb52e7880c1550fda1720671f76c7229a80bae). C'est environ **135 MiB** avec des données commençant en août.

**Comment by HorlogeSkynet** [comment]
Très bien, donc pas de projet de les publier dans le futur si j'ai bien compris ?
Je ne te cache pas que je suis un peu curieux de savoir comment cela fonctionne !

Je ne savais pas que GitHub s'était mêlé de cela, mais ça reste compréhensible, car c'est une forme de fliquage 😜

Au plaisir de se croiser sur Montréal _then_ 😄

**Comment by millette** [comment]
J'ai d'autres projets similaires avec les sources disponibles:

* https://streaker.rollodeqc.com/today
* http://www.rollodeqc.com/ (lien vers les autres projets, faq, etc.)

Les sources de ces projets sont disponbles dans mon compte personnel:
<https://github.com/millette?utf8=%E2%9C%93&tab=repositories&q=rollodeqc&type=&language=>

Pour ce qui est de ghqc, je cherche les utilisateurs du Québec (location = québec, quebec, qc, montréal, montreal, mtl, yul) et ghqc follow chacun des users trouvé. Ensuite, je peux poller un fil des événements de tous ces users d'un coup, au lieu de devoir poller 12,500 comptes l'un après l'autre. GitHub a compris que ça sauvait des ressources de procéder ainsi et m'ont gentiment permis cette exception.

**Comment by HorlogeSkynet** [comment]
Ah d'accord ! J'avais en fait _checker_ l'organisation **RollodeQC** sur GitHub, mais pas ton compte perso', désolé...

Je ferme ceci alors, merci pour les réponses rapides, et les infos 🙇 (et merci GitHub)

**Comment by batarmanrookie** [comment]
Ce serait une joie pour moi de contribuer aux y’a[Upp]() pour moi de pouvoir contribuer à mon média favori dans ma langue natale, Je pourrait
