### ISSUE TITLE
Je ne comprends pas le but de ce bot

### ISSUE THREAD

**Issue by XsongyangX** [ghqc/readme#10]
Mon réflexe initiale était de bloquer ce suiveur... Si vous pouvez justifier l'existence de ce bot d'une manière plus concrète que l'envie de poursuivre des étrangers, ce bot aurait plus de sens.

**Comment by millette** [comment]
Bonjour @XsongyangX 

Ce bot, en suivant les 22,000 utilisateurs du Québec, permet d'obtenir les événements liés à ces comptes en un seul appel (liste des derniers événements des utilisateurs qu'on _follow_) au lieu de devoir faire un appel par utilisateurs (à intervals réguliers).

Ces données pourraient servir à 

* https://streaker.rollodeqc.com/today
* http://dev.rollodeqc.com/fr/

Ça me permettra de faire bientôt des statistiques/graphiques sur l'impact de covid-19 sur le développement au Québec et les logiciels libres en particulier.

Bref, c'est une initiative personnelle pour mieux collecter des données publiques et faire une trace globale dans le temps.

J'espère que ça répond un peu à ta question.

**Comment by XsongyangX** [comment]
Ah OK, c'est quelque chose en lien avec le coronavirus. Je ne m'attendais pas à ça. Pardon si je sonnais trop méchant ;P
